"""Output handlers — post-process / persist a capability's result.

A handler receives the validated model result plus the run context and writes
whatever records it needs, returning a small summary the caller can show.
"""
import re
import uuid
from datetime import datetime

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.entity_record import EntityRecord


def _slug(name: str) -> str:
    base = re.sub(r"[^A-Za-z0-9]+", "-", name or "").strip("-").upper()[:14]
    return base or "PROJECT"


async def persist_project_plan(db: AsyncSession, *, result: dict, context: dict,
                               actor: uuid.UUID, org: uuid.UUID,
                               module_code: str | None = None, entity_type: str | None = None) -> dict:
    """Persist an auto-planned project as pm_projects / pm_milestones / pm_tasks.

    Linking is by code (the PM schema convention): all records share one
    project_code; each task's parent_task_code points at its milestone.
    """
    plan = result
    project_code = f"{_slug(plan.get('project_name'))}-{uuid.uuid4().hex[:4].upper()}"
    today = context.get("today", "")

    def rec(entity_type: str, data: dict) -> EntityRecord:
        return EntityRecord(
            entity_type=entity_type, module_code="pm", data=data,
            organization_id=org, created_by=actor, last_modified_by=actor,
        )

    records: list[EntityRecord] = []
    project = rec("pm_projects", {
        "project_code": project_code,
        "project_name": plan.get("project_name", "Untitled Project"),
        "description": plan.get("description", ""),
        "project_manager": plan.get("project_manager", ""),
        "client_name": plan.get("client_name", ""),
        "department": plan.get("department", ""),
        "priority": plan.get("priority", "medium"),
        "status": "planning",
        "start_date": plan.get("start_date", today),
        "end_date": plan.get("end_date", ""),
        "budget": plan.get("estimated_budget", 0),
        "actual_cost": 0,
        "progress_percentage": 0,
        "notes": "Generated by AI auto-planner.",
    })
    records.append(project)

    milestones = plan.get("milestones") or []
    milestone_codes: list[str] = []
    for i, m in enumerate(milestones):
        code = f"{project_code}-M{i + 1:02d}"
        milestone_codes.append(code)
        records.append(rec("pm_milestones", {
            "milestone_code": code,
            "milestone_name": m.get("milestone_name", f"Milestone {i + 1}"),
            "project_code": project_code,
            "description": m.get("description", ""),
            "due_date": m.get("due_date", ""),
            "deliverables": m.get("deliverables", ""),
            "owner": m.get("owner", ""),
            "status": "pending",
        }))

    tasks = plan.get("tasks") or []
    for i, t in enumerate(tasks):
        idx = t.get("milestone_index")
        parent = milestone_codes[idx] if isinstance(idx, int) and 0 <= idx < len(milestone_codes) else ""
        records.append(rec("pm_tasks", {
            "task_code": f"{project_code}-T{i + 1:02d}",
            "task_name": t.get("task_name", f"Task {i + 1}"),
            "project_code": project_code,
            "description": t.get("description", ""),
            "assigned_to": t.get("assigned_to", ""),
            "priority": t.get("priority", "medium"),
            "status": "todo",
            "start_date": t.get("start_date", ""),
            "due_date": t.get("due_date", ""),
            "estimated_hours": t.get("estimated_hours", 0),
            "actual_hours": 0,
            "progress_percentage": 0,
            "parent_task_code": parent,
            "notes": "",
        }))

    for r in records:
        db.add(r)
    await db.commit()
    await db.refresh(project)

    return {
        "project_id": str(project.id),
        "project_code": project_code,
        "project_name": project.data.get("project_name"),
        "counts": {"milestones": len(milestones), "tasks": len(tasks)},
    }


async def persist_entity_record(db: AsyncSession, *, result: dict, context: dict,
                                actor: uuid.UUID, org: uuid.UUID,
                                module_code: str | None = None, entity_type: str | None = None) -> dict:
    """Persist an AI-drafted record (the `create_record` action) into its section."""
    if not entity_type:
        raise ValueError("entity_type is required to create a record")
    # Keep only real, non-empty fields of this section (drop any invented keys).
    from . import fielddefs
    allowed = fielddefs.allowed_names(await fielddefs.get_fields(db, entity_type))
    data = {k: v for k, v in (result or {}).items() if v not in (None, "") and (not allowed or k in allowed)}
    if not data:
        raise ValueError("The draft had no usable fields to save")
    # Map reference-field text (e.g. "Cash account") to real record ids.
    data = await fielddefs.resolve_references(db, entity_type, data, module_code)
    rec = EntityRecord(entity_type=entity_type, module_code=module_code or "core", data=data,
                       organization_id=org, created_by=actor, last_modified_by=actor)
    db.add(rec)
    await db.commit()
    await db.refresh(rec)
    label = next((str(data[f]) for f in (
        "name", "title", "full_name", "candidate_name", "applicant_name", "employee_name",
        "subject", "job_title", "position", "reference", "reference_number", "description",
    ) if data.get(f)), entity_type)
    return {"id": str(rec.id), "entity_type": entity_type, "label": label, "fields": data}


async def update_entity_record(db: AsyncSession, *, result: dict, context: dict,
                               actor: uuid.UUID, org: uuid.UUID,
                               module_code: str | None = None, entity_type: str | None = None) -> dict:
    """Apply AI-drafted changes to an existing record (the `update_record` action)."""
    record_id = (result or {}).get("record_id")
    changes = (result or {}).get("changes") or {}
    if not record_id:
        raise ValueError("No target record was identified to update")
    rec = await db.get(EntityRecord, uuid.UUID(str(record_id)))
    if not rec or rec.is_deleted == "Y":
        raise ValueError("The record to update was not found")
    et = entity_type or rec.entity_type

    from . import fielddefs
    allowed = fielddefs.allowed_names(await fielddefs.get_fields(db, et))
    clean = {k: v for k, v in changes.items() if v not in (None, "") and (not allowed or k in allowed)}
    if not clean:
        raise ValueError("No valid field changes to apply")
    clean = await fielddefs.resolve_references(db, et, clean, module_code)

    rec.data = {**(rec.data or {}), **clean}
    rec.last_modified_by = actor
    rec.last_modified_at = datetime.utcnow()
    await db.commit()
    await db.refresh(rec)
    label = next((str(rec.data[f]) for f in ("name", "title", "reference", "transaction_number") if rec.data.get(f)), et)
    return {"id": str(rec.id), "label": label, "updated": list(clean.keys()), "fields": clean}


HANDLERS = {
    "persist_project_plan": persist_project_plan,
    "persist_entity_record": persist_entity_record,
    "update_entity_record": update_entity_record,
}
