'use client';

import EntityList from '@shared/components/EntityList';

/**
 * Messages — internal messaging inbox. Read-only listing; messages are
 * generated by other actions and the per-thread compose view is not part
 * of the list scope.
 */
export default function MessagesPage() {
  return (
    <EntityList
      entityType="messages"
      title="Messages"
      readOnly
    />
  );
}
